export const mockCredits = [
  {
    id: "1",
    projectName: "Sundarbans Mangrove Restoration",
    ecosystem: "mangrove",
    location: "Bangladesh",
    price: 25,
    availableCredits: 5000,
    sequestrationRate: 4.2,
    verificationStatus: "verified" as const,
    developerId: "dev-001",
    image: "🌊",
    dateAdded: "2024-06-01",
    lastUpdated: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    dataQuality: { overall: 98, confidence: 98, source: "blockchain", dataAge: 5 },
  },
  {
    id: "2",
    projectName: "Seagrass Meadow Conservation",
    ecosystem: "seagrass",
    location: "Australia",
    price: 18,
    availableCredits: 8000,
    sequestrationRate: 6.5,
    verificationStatus: "verified" as const,
    developerId: "dev-002",
    image: "🌿",
    dateAdded: "2024-06-05",
    lastUpdated: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    dataQuality: { overall: 95, confidence: 95, source: "satellite", dataAge: 10 },
  },
  {
    id: "3",
    projectName: "Atlantic Salt Marsh Protection",
    ecosystem: "saltmarsh",
    location: "USA",
    price: 22,
    availableCredits: 3500,
    sequestrationRate: 1.8,
    verificationStatus: "verified" as const,
    developerId: "dev-003",
    image: "🌾",
    dateAdded: "2024-06-10",
    lastUpdated: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    dataQuality: { overall: 97, confidence: 97, source: "ground sensors", dataAge: 15 },
  },
  {
    id: "4",
    projectName: "Kelp Forest Restoration Initiative",
    ecosystem: "kelp",
    location: "Norway",
    price: 28,
    availableCredits: 2200,
    sequestrationRate: 3.8,
    verificationStatus: "pending" as const,
    developerId: "dev-004",
    image: "🌊",
    dateAdded: "2024-06-08",
    lastUpdated: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    dataQuality: { overall: 96, confidence: 96, source: "blockchain", dataAge: 20 },
  },
  {
    id: "5",
    projectName: "Mekong Delta Mangrove Expansion",
    ecosystem: "mangrove",
    location: "Vietnam",
    price: 20,
    availableCredits: 6500,
    sequestrationRate: 4.0,
    verificationStatus: "verified" as const,
    developerId: "dev-005",
    image: "🌳",
    dateAdded: "2024-06-03",
    lastUpdated: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
    dataQuality: { overall: 99, confidence: 99, source: "blockchain", dataAge: 25 },
  },
  {
    id: "6",
    projectName: "Mediterranean Seagrass Recovery",
    ecosystem: "seagrass",
    location: "Spain",
    price: 19,
    availableCredits: 4000,
    sequestrationRate: 5.2,
    verificationStatus: "auditing" as const,
    developerId: "dev-006",
    image: "🌿",
    dateAdded: "2024-06-12",
    lastUpdated: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
    dataQuality: { overall: 94, confidence: 94, source: "satellite", dataAge: 30 },
  },
]

export const mockTransactions = [
  {
    id: "tx-1",
    projectName: "Sundarbans Mangrove Restoration",
    quantity: 500,
    pricePerUnit: 25,
    totalAmount: 12500,
    status: "confirmed" as const,
    hash: "0x1234567890abcdef1234567890abcdef12345678",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "tx-2",
    projectName: "Seagrass Meadow Conservation",
    quantity: 300,
    pricePerUnit: 18,
    totalAmount: 5400,
    status: "confirmed" as const,
    hash: "0x9876543210fedcba9876543210fedcba98765432",
    timestamp: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "tx-3",
    projectName: "Atlantic Salt Marsh Protection",
    quantity: 200,
    pricePerUnit: 22,
    totalAmount: 4400,
    status: "pending" as const,
    hash: "0xabcdef1234567890abcdef1234567890abcdef12",
    timestamp: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockNotifications = [
  {
    id: "notif-1",
    type: "transaction_confirmed",
    title: "Purchase Confirmed",
    message: "Your purchase of 500 credits from Sundarbans project has been confirmed",
    timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: "notif-2",
    type: "price_alert",
    title: "Price Alert",
    message: "Seagrass credits dropped to $18 - below your target price",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    read: false,
  },
  {
    id: "notif-3",
    type: "new_project",
    title: "New Project Available",
    message: "Mediterranean Seagrass Recovery project is now available for purchase",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    read: false,
  },
]

export const mockDeveloperProjects = [
  {
    id: "dev-proj-1",
    projectName: "Sundarbans Mangrove Restoration",
    ecosystem: "mangrove",
    location: "Bangladesh",
    developerId: "dev-001",
    status: "active" as const,
    creditsGenerated: 2450,
    creditsVerified: 2300,
    creditsPending: 150,
    monthlyGeneration: 245,
    areaUnderManagement: 1250,
    co2SequesteredTotal: 10250,
    verificationProgress: 94,
    nextAuditDate: "2024-07-15",
    startDate: "2024-01-01",
    image: "🌊",
  },
  {
    id: "dev-proj-2",
    projectName: "Atlantic Salt Marsh Protection",
    ecosystem: "saltmarsh",
    location: "USA",
    developerId: "dev-003",
    status: "active" as const,
    creditsGenerated: 1850,
    creditsVerified: 1750,
    creditsPending: 100,
    monthlyGeneration: 185,
    areaUnderManagement: 850,
    co2SequesteredTotal: 7500,
    verificationProgress: 95,
    nextAuditDate: "2024-08-01",
    startDate: "2024-02-01",
    image: "🌾",
  },
]

export const mockMrvData = [
  { month: "Jan", creditsGenerated: 200, creditsVerified: 190, monitored: 95 },
  { month: "Feb", creditsGenerated: 220, creditsVerified: 210, monitored: 96 },
  { month: "Mar", creditsGenerated: 240, creditsVerified: 230, monitored: 97 },
  { month: "Apr", creditsGenerated: 245, creditsVerified: 235, monitored: 98 },
  { month: "May", creditsGenerated: 260, creditsVerified: 250, monitored: 98 },
  { month: "Jun", creditsGenerated: 280, creditsVerified: 265, monitored: 99 },
]

export const mockFieldSiteData = [
  {
    id: "site-1",
    name: "North Plot",
    ecosystem: "mangrove",
    areaHa: 450,
    co2Sequestered: 1890,
    biodiversityScore: 8.5,
    waterQuality: "Good",
    lastMonitored: "2024-06-10",
  },
  {
    id: "site-2",
    name: "Central Plot",
    ecosystem: "mangrove",
    areaHa: 400,
    co2Sequestered: 1680,
    biodiversityScore: 8.2,
    waterQuality: "Good",
    lastMonitored: "2024-06-12",
  },
  {
    id: "site-3",
    name: "South Plot",
    ecosystem: "mangrove",
    areaHa: 400,
    co2Sequestered: 1680,
    biodiversityScore: 7.9,
    waterQuality: "Fair",
    lastMonitored: "2024-06-08",
  },
]

export const mockCommunityProjects = [
  {
    id: "comm-proj-1",
    projectName: "Sundarbans Mangrove Restoration",
    location: "Bangladesh",
    ecosystem: "mangrove",
    communitySize: 2450,
    beneficiaries: 1840,
    image: "🌊",
    startDate: "2024-01-01",
    status: "active" as const,
  },
  {
    id: "comm-proj-2",
    projectName: "Atlantic Salt Marsh Protection",
    location: "USA",
    ecosystem: "saltmarsh",
    communitySize: 850,
    beneficiaries: 680,
    image: "🌾",
    startDate: "2024-02-01",
    status: "active" as const,
  },
  {
    id: "comm-proj-3",
    projectName: "Seagrass Meadow Conservation",
    location: "Australia",
    ecosystem: "seagrass",
    communitySize: 1200,
    beneficiaries: 950,
    image: "🌿",
    startDate: "2024-03-15",
    status: "active" as const,
  },
]

export const mockFieldDataCollections = [
  {
    id: "field-1",
    siteId: "site-1",
    projectName: "Sundarbans Mangrove Restoration",
    location: "North Plot",
    dateCollected: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    collectorName: "Rajesh Kumar",
    measurements: {
      waterTemperature: 28.5,
      salinity: 32.2,
      phLevel: 7.8,
      biodiversitySpecies: 24,
      healthStatus: "Healthy" as const,
    },
    dataType: "Water Quality",
  },
  {
    id: "field-2",
    siteId: "site-2",
    projectName: "Sundarbans Mangrove Restoration",
    location: "Central Plot",
    dateCollected: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    collectorName: "Priya Singh",
    measurements: {
      waterTemperature: 27.9,
      salinity: 31.8,
      phLevel: 7.9,
      biodiversitySpecies: 26,
      healthStatus: "Excellent" as const,
    },
    dataType: "Biodiversity Survey",
  },
  {
    id: "field-3",
    siteId: "site-3",
    projectName: "Sundarbans Mangrove Restoration",
    location: "South Plot",
    dateCollected: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    collectorName: "Amit Patel",
    measurements: {
      waterTemperature: 28.1,
      salinity: 32.0,
      phLevel: 7.7,
      biodiversitySpecies: 22,
      healthStatus: "Monitoring" as const,
    },
    dataType: "Water Quality",
  },
]

export const mockBenefitDistribution = [
  {
    id: "benefit-1",
    projectName: "Sundarbans Mangrove Restoration",
    distributionDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    totalBudget: 150000,
    beneficiariesReached: 1840,
    benefitType: "Cash Transfer",
    amountPerBeneficiary: 81.52,
    status: "completed" as const,
  },
  {
    id: "benefit-2",
    projectName: "Sundarbans Mangrove Restoration",
    distributionDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    totalBudget: 85000,
    beneficiariesReached: 1840,
    benefitType: "Training Programs",
    amountPerBeneficiary: 46.2,
    status: "completed" as const,
  },
  {
    id: "benefit-3",
    projectName: "Sundarbans Mangrove Restoration",
    distributionDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    totalBudget: 120000,
    beneficiariesReached: 1840,
    benefitType: "Healthcare Services",
    amountPerBeneficiary: 65.22,
    status: "pending" as const,
  },
]

export const mockAuditRecords = [
  {
    id: "audit-1",
    projectName: "Sundarbans Mangrove Restoration",
    projectId: "dev-proj-1",
    auditDate: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    auditorName: "Dr. Sarah Johnson",
    status: "completed" as const,
    complianceScore: 98,
    creditsVerified: 2300,
    creditsRejected: 50,
    findings: "Full compliance. Minor documentation updates recommended.",
    nextReviewDate: "2024-09-15",
  },
  {
    id: "audit-2",
    projectName: "Atlantic Salt Marsh Protection",
    projectId: "dev-proj-2",
    auditDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    auditorName: "Dr. Michael Chen",
    status: "in-progress" as const,
    complianceScore: 85,
    creditsVerified: 1500,
    creditsRejected: 250,
    findings: "Review in progress. MRV data verification ongoing.",
    nextReviewDate: "2024-08-20",
  },
  {
    id: "audit-3",
    projectName: "Mediterranean Seagrass Recovery",
    projectId: "dev-006",
    auditDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    auditorName: "Dr. Elena Rodriguez",
    status: "scheduled" as const,
    complianceScore: 0,
    creditsVerified: 0,
    creditsRejected: 0,
    findings: "Audit scheduled. Awaiting project documentation.",
    nextReviewDate: "2024-08-05",
  },
]

export const mockComplianceViolations = [
  {
    id: "viol-1",
    projectName: "Kelp Forest Restoration Initiative",
    violationType: "data-discrepancy",
    severity: "medium" as const,
    description: "CO2 sequestration values do not match satellite data",
    reportedDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "investigating" as const,
    resolution: "Awaiting project response",
  },
  {
    id: "viol-2",
    projectName: "Mekong Delta Mangrove Expansion",
    violationType: "boundary-change",
    severity: "low" as const,
    description: "Project area boundary updated without prior notification",
    reportedDate: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "resolved" as const,
    resolution: "Properly documented and approved",
  },
  {
    id: "viol-3",
    projectName: "Atlantic Salt Marsh Protection",
    violationType: "monitoring-gap",
    severity: "high" as const,
    description: "30-day gap in field monitoring data collection",
    reportedDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    status: "investigating" as const,
    resolution: "Under investigation - equipment malfunction suspected",
  },
]

export const mockRegulatoryReports = [
  {
    id: "report-1",
    month: "January",
    year: 2024,
    projectsAudited: 2,
    creditsVerified: 4200,
    creditsRejected: 280,
    complianceRate: 93.7,
    violationsFound: 1,
  },
  {
    id: "report-2",
    month: "February",
    year: 2024,
    projectsAudited: 3,
    creditsVerified: 5100,
    creditsRejected: 350,
    complianceRate: 93.6,
    violationsFound: 2,
  },
  {
    id: "report-3",
    month: "March",
    year: 2024,
    projectsAudited: 2,
    creditsVerified: 3800,
    creditsRejected: 200,
    complianceRate: 95.0,
    violationsFound: 0,
  },
  {
    id: "report-4",
    month: "April",
    year: 2024,
    projectsAudited: 4,
    creditsVerified: 6400,
    creditsRejected: 420,
    complianceRate: 93.8,
    violationsFound: 1,
  },
]

export const mockPriceHistory = [
  { date: "2024-01-01", mangrove: 22, seagrass: 16, saltmarsh: 19, kelp: 24 },
  { date: "2024-02-01", mangrove: 23, seagrass: 17, saltmarsh: 20, kelp: 25 },
  { date: "2024-03-01", mangrove: 24, seagrass: 18, saltmarsh: 21, kelp: 26 },
  { date: "2024-04-01", mangrove: 25, seagrass: 18, saltmarsh: 22, kelp: 27 },
  { date: "2024-05-01", mangrove: 25, seagrass: 19, saltmarsh: 22, kelp: 28 },
  { date: "2024-06-01", mangrove: 26, seagrass: 19, saltmarsh: 23, kelp: 28 },
]

export const mockCreditsIssuedTrend = [
  { month: "Jan", issued: 3200, retired: 1200, retired_pct: 37.5 },
  { month: "Feb", issued: 3500, retired: 1400, retired_pct: 40 },
  { month: "Mar", issued: 3800, retired: 1600, retired_pct: 42.1 },
  { month: "Apr", issued: 4100, retired: 1800, retired_pct: 43.9 },
  { month: "May", issued: 4400, retired: 2000, retired_pct: 45.5 },
  { month: "Jun", issued: 4700, retired: 2200, retired_pct: 46.8 },
]

export const mockImpactMetrics = [
  { month: "Jan", co2Sequestered: 12500, biodiversityScore: 7.2, communityBenefits: 45000 },
  { month: "Feb", co2Sequestered: 13200, biodiversityScore: 7.4, communityBenefits: 52000 },
  { month: "Mar", co2Sequestered: 14100, biodiversityScore: 7.6, communityBenefits: 60000 },
  { month: "Apr", co2Sequestered: 15000, biodiversityScore: 7.8, communityBenefits: 68000 },
  { month: "May", co2Sequestered: 16200, biodiversityScore: 7.9, communityBenefits: 78000 },
  { month: "Jun", co2Sequestered: 17500, biodiversityScore: 8.1, communityBenefits: 89000 },
]

export const mockMarketIntelligence = [
  {
    id: "intel-1",
    title: "Rising Demand for Mangrove Credits",
    category: "market-trend",
    impact: "high",
    description: "Mangrove ecosystem credits seeing 15% monthly price growth due to increased corporate commitments",
    date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "intel-2",
    title: "New Seagrass Verification Protocol",
    category: "regulatory",
    impact: "medium",
    description: "Updated MRV standards approved for seagrass projects. Implementation deadline: 90 days.",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "intel-3",
    title: "Climate Investment Fund Announcement",
    category: "funding",
    impact: "high",
    description: "New $100M climate fund allocated for blue carbon projects across Asia-Pacific region",
    date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockPortfolioAnalytics = [
  {
    id: "portfolio-1",
    projectName: "Sundarbans Mangrove Restoration",
    ecosystem: "mangrove",
    location: "Bangladesh",
    holdingsValue: 125000,
    yearlyImpact: 2400,
    pricePerCredit: 25,
    riskProfile: "low" as const,
    diversificationScore: 8.5,
    recommendation: "Strong holding with stable growth",
  },
  {
    id: "portfolio-2",
    projectName: "Seagrass Meadow Conservation",
    ecosystem: "seagrass",
    location: "Australia",
    holdingsValue: 144000,
    yearlyImpact: 1950,
    pricePerCredit: 18,
    riskProfile: "medium" as const,
    diversificationScore: 8.2,
    recommendation: "Good growth potential with moderate volatility",
  },
  {
    id: "portfolio-3",
    projectName: "Kelp Forest Restoration Initiative",
    ecosystem: "kelp",
    location: "Norway",
    holdingsValue: 56000,
    yearlyImpact: 760,
    pricePerCredit: 28,
    riskProfile: "medium" as const,
    diversificationScore: 7.8,
    recommendation: "High-value emerging opportunity",
  },
]

export const mockDataCollections = [
  {
    id: "data-1",
    location: "Sundarbans Mangrove Zone A",
    type: "satellite" as const,
    timestamp: "2024-01-15T14:30:00",
    status: "completed" as const,
    data: { co2Captured: 450, coverage: 98.5, accuracy: 96, biodiversity: 87 },
  },
  {
    id: "data-2",
    location: "Seagrass Meadow Site B",
    type: "drone" as const,
    timestamp: "2024-01-15T13:45:00",
    status: "processing" as const,
    data: { co2Captured: 320, coverage: 85, accuracy: 94, biodiversity: 92 },
  },
  {
    id: "data-3",
    location: "Salt Marsh Estuary C",
    type: "sensor" as const,
    timestamp: "2024-01-15T12:00:00",
    status: "active" as const,
    data: { co2Captured: 280, coverage: 100, accuracy: 98, biodiversity: 78 },
  },
]

export const mockValidationRecords = [
  {
    id: "val-1",
    creditBatch: "SMR-2024-06-001",
    dataSource: "Satellite + Ground Sensors",
    submissionDate: "2024-06-15T10:30:00",
    validationStatus: "verified" as const,
    smartContractHash: "0x7a2c8f9e1d4b6c3e5f2a8b9d7c6e4f1a",
    verificationAccuracy: 98.5,
    dataPoints: 24580,
    estimatedCredits: 2450,
  },
  {
    id: "val-2",
    creditBatch: "SGM-2024-06-015",
    dataSource: "Drone Imagery + Field Data",
    submissionDate: "2024-06-14T14:45:00",
    validationStatus: "validating" as const,
    smartContractHash: "0x3e9f1c7d4b2a6e8f5c3d1a9b7e6f4c2a",
    verificationAccuracy: 0,
    dataPoints: 18920,
    estimatedCredits: 1892,
  },
]

export const mockWalletState = {
  address: "0x1234567890abcdef1234567890abcdef12345678",
  balance: 15.5,
  ethValue: 31250,
  connectedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  networkVerified: true,
}

export const mockNetworkStatus = {
  chain: "Ethereum Mainnet",
  chainId: 1,
  status: "healthy",
  blockTime: 12.5,
  lastBlock: 19284726,
  gasPrice: {
    standard: 35,
    fast: 42,
    urgent: 55,
  },
  lastUpdated: new Date().toISOString(),
}

export const mockWalletTransactions = [
  {
    id: "tx-001",
    hash: "0xabcd1234ef5678gh...",
    type: "buy",
    credits: 500,
    amount: 12500,
    project: "Sundarbans Mangrove Restoration",
    status: "confirmed",
    confirmations: 15,
    gasUsed: 0.0082,
    timestamp: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    blockNumber: 19284710,
  },
  // ... more mock transactions ...
]
